FROM apache/airflow:2.7.1

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --chown=airflow:root requirements.txt /requirements.txt

USER airflow
RUN pip install --no-cache-dir -r /requirements.txt
